move_group:
  ros__parameters:
    planning_plugin: ompl_interface/OMPLPlanner
    request_adapters:
      - default_planning_request_adapters/ResolveConstraintFrames
      - default_planning_request_adapters/ValidateWorkspaceBounds
      - default_planning_request_adapters/CheckStartStateBounds
      - default_planning_request_adapters/CheckStartStateCollision
    response_adapters:
      - default_planning_response_adapters/AddTimeOptimalParameterization
      - default_planning_response_adapters/ValidateSolution
      - default_planning_response_adapters/DisplayMotionPath
    white_arm:
      default_planner_config: RRTConnectkConfigDefault
      planner_configs:
        - RRTConnectkConfigDefault
    black_arm:
      default_planner_config: RRTConnectkConfigDefault
      planner_configs:
        - RRTConnectkConfigDefault
    planner_configs:
      RRTConnectkConfigDefault:
        type: geometric::RRTConnect
        range: 0.0
