controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fr3_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    fr3_hand_controller:
      type: position_controllers/GripperActionController

fr3_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7

fr3_hand_controller:
  ros__parameters:
    joint: fr3_finger_joint1
